const CONFIG = {
    SUPABASE_URL: 'https://uerrkhupgcroosftthrh.supabase.co',
    SUPABASE_KEY: 'eyJhbGciOiJFUzI1NiIsImtpZCI6IjFiZTE2ODFhLWI4MzktNDQ5Mi05ZWU0LTNjNWU3MjM4NDU4NSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3VlcnJraHVwZ2Nyb29zZnR0aHJoLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJjMmY3YWRmNS00YmMzLTQ4OGYtOTViOC1mMzc0ZGZmNjZjYjkiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgzNjk3ODE4LCJpYXQiOjE3ODM2OTQyMTgsImVtYWlsIjoiYWRtaW5AbWIzZC5jeiIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsicm9sZSI6ImFkbWluIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3ODM2OTQyMTh9XSwic2Vzc2lvbl9pZCI6ImU3NjBiZDc4LWU1YzEtNDdmYi1iMzgzLTc3NDk0ZTc5MGI1ZiIsImlzX2Fub255bW91cyI6ZmFsc2V9.oPgKJrLiRQYNBQr35A5WpjGsF2BXQo08nUE6HcPazCitaKCjX-b74vis7a3WOKwVm7f3HqgNtxfSsIG-M0gygg'
};

window.supabase = window.supabase.createClient(CONFIG.SUPABASE_URL, CONFIG.SUPABASE_KEY);

console.log('Supabase inicializován');
console.log('Auth:', !!window.supabase.auth);